services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Framework\Module\Setting\SettingDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Module\Setting\SettingDao
